[build-system]
requires = [
    "setuptools>=64",
    "setuptools-scm>=8",
]
build-backend = "setuptools.build_meta"

[project]
name = "commitdev"
dynamic = ["version"]
dependencies = [
    "typer",
    "requests",
]

[project.scripts]
cdv = "commitdev.main:app"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"